
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = ',\xe0D\xd0\x06\x17\x84b\r\x1a[\xf1\x08N\x9d!'
    
_lr_action_items = {'RPAREN':([2,4,5,6,7,8,9,10,],[-4,-3,-2,-5,-3,10,-3,-7,]),'CHAR':([0,1,2,4,5,6,7,8,9,10,],[2,2,-4,2,2,-5,2,2,2,-7,]),'LPAREN':([0,1,2,4,5,6,7,8,9,10,],[4,4,-4,4,4,-5,4,4,4,-7,]),'STAR':([0,1,2,4,5,6,7,8,9,10,],[-3,6,-4,-3,6,-5,-3,6,6,-7,]),'OR':([0,1,2,4,5,6,7,8,9,10,],[-3,7,-4,-3,7,-5,-3,7,7,-7,]),'$end':([0,1,2,3,5,6,7,9,10,],[-3,-1,-4,0,-2,-5,-3,-3,-7,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'regex':([0,1,4,5,7,8,9,],[1,5,8,5,9,5,5,]),'r':([0,],[3,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> r","S'",1,None,None,None),
  ('r -> regex','r',1,'p_r','cs262_final_9.py',91),
  ('regex -> regex regex','regex',2,'p_regex','cs262_final_9.py',95),
  ('regex -> <empty>','regex',0,'p_regex_empty','cs262_final_9.py',99),
  ('regex -> CHAR','regex',1,'p_regex_char','cs262_final_9.py',103),
  ('regex -> regex STAR','regex',2,'p_regex_star','cs262_final_9.py',107),
  ('regex -> regex OR regex','regex',3,'p_regex_or','cs262_final_9.py',111),
  ('regex -> LPAREN regex RPAREN','regex',3,'p_regex_paran','cs262_final_9.py',115),
]
